server:
  port: 5002
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/esd_mini_project?serverTimezone=UTC&useSSL=false&autoReconnect=true
    username: speproject
    password: speproject



eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
